# Generated by Django 4.2.5 on 2023-10-15 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(max_length=255)),
                ('enrollment_start', models.DateField()),
                ('enrollment_end', models.DateField()),
                ('course_start', models.DateField()),
                ('course_end', models.DateField()),
                ('lab_time', models.CharField(max_length=255)),
                ('lab_day', models.CharField(max_length=255)),
                ('lecture_time', models.CharField(max_length=255)),
                ('lecture_day', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
