# Generated by Django 4.2.5 on 2023-10-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_announcements_text_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
