# Generated by Django 4.2.5 on 2023-10-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_courses_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
