# Generated by Django 4.2.5 on 2023-09-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
