# Generated by Django 4.2.5 on 2023-09-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_teachers_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={},
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='user_permissions',
        ),
    ]
