# Generated by Django 4.2.5 on 2023-09-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_teachers_options_teachers_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='lastname',
        ),
    ]
