# Generated by Django 4.2.5 on 2023-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_teachers_firstname_remove_teachers_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
