# Generated by Django 4.2.5 on 2023-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_teachers_first_name_alter_teachers_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
